"use client";
import { useRef } from "react";
import type { WorkspaceData } from "@/modules/dashboard";
import { CommandButton, CommandForm } from "@/shared/components/command-form";
import { Badge, Panel, quantity, currency, label, date, Empty, Table } from "@/shared/components/display";
export function OrderDetail({data:d,id}:{data:WorkspaceData;id:string}) {
 const order=d.orders.find(o=>o.id===id);const receiptKey=useRef("");
 if(!order)return <Empty>Pedido não encontrado.</Empty>;
 const buyer=["OWNER","ADMIN","BUYER"].includes(d.user.role),admin=["OWNER","ADMIN"].includes(d.user.role),operator=["OWNER","ADMIN","OPERATOR"].includes(d.user.role);
 const remaining=order.items.filter(i=>Number(i.remainingQuantity)>0);
 return <><Panel title={`Pedido #${order.id.slice(-6).toUpperCase()}`} description={order.supplier.name}><div className="order-overview"><Badge value={order.status}/><strong>{currency(order.total)}</strong><span>Frete: {currency(order.freight)}</span></div><p>Motivo da escolha: {order.selectionReason??"—"}</p><Table headers={["Ingrediente","Pedido","Recebido","Preço unitário","Total"]}>{order.items.map(i=><tr key={i.id}><td>{i.product.name}</td><td>{quantity(i.quantity)} {label(i.product.unit)}</td><td>{quantity(i.receivedQuantity)} {label(i.product.unit)}</td><td>{currency(i.unitPrice)}</td><td>{currency(i.totalPrice)}</td></tr>)}</Table><div className="actions-row">{order.status==="DRAFT"&&buyer&&<CommandButton command="transitionPurchaseOrder" payload={{id:order.id,status:"PENDING_APPROVAL"}}>Solicitar aprovação</CommandButton>}{order.status==="PENDING_APPROVAL"&&admin&&<CommandButton command="transitionPurchaseOrder" payload={{id:order.id,status:"APPROVED"}} variant="default">Aprovar compra</CommandButton>}{order.status==="APPROVED"&&buyer&&<CommandButton command="transitionPurchaseOrder" payload={{id:order.id,status:"ORDERED"}} variant="default">Confirmar pedido ao fornecedor</CommandButton>}{!["RECEIVED","PARTIALLY_RECEIVED","CANCELED"].includes(order.status)&&admin&&<CommandButton command="transitionPurchaseOrder" payload={{id:order.id,status:"CANCELED"}} variant="destructive">Cancelar pedido</CommandButton>}</div></Panel>{["ORDERED","PARTIALLY_RECEIVED"].includes(order.status)&&operator&&<Panel title="Receber ingredientes" description="Registre apenas o que chegou. Estoque, custo médio, histórico de preço e conta a pagar serão atualizados juntos."><CommandForm key={order.receipts.length} command="receivePurchaseOrder" fields={[]} transform={v=>{receiptKey.current ||=crypto.randomUUID();return {id:order.id,idempotencyKey:receiptKey.current,items:remaining.filter(i=>Number(v[`received_${i.id}`])>0).map(i=>({orderItemId:i.id,quantity:v[`received_${i.id}`]}))};}} onSuccess={()=>{receiptKey.current="";}} submit="Confirmar recebimento"><div className="wide-field table-scroll"><table><thead><tr><th>Ingrediente</th><th>Falta receber</th><th>Chegou agora</th></tr></thead><tbody>{remaining.map(i=><tr key={i.id}><td>{i.product.name}</td><td>{quantity(i.remainingQuantity)} {label(i.product.unit)}</td><td><input aria-label={`Receber ${i.product.name}`} name={`received_${i.id}`} type="number" step="0.0001" min="0" max={i.remainingQuantity} defaultValue={i.remainingQuantity} required/></td></tr>)}</tbody></table></div></CommandForm></Panel>}<Panel title="Recebimentos registrados">{order.receipts.length===0?<Empty>O pedido ainda não teve recebimentos.</Empty>:<Table headers={["Data","Valor recebido","Referência"]}>{order.receipts.map(r=><tr key={r.id}><td>{date(r.receivedAt)}</td><td>{currency(r.total)}</td><td>#{r.id.slice(-6)}</td></tr>)}</Table>}</Panel></>;
}
