"use client";
import { useState } from "react";
import type { WorkspaceData } from "@/modules/dashboard";
import { CommandForm } from "@/shared/components/command-form";
import { Panel, label, quantity } from "@/shared/components/display";
export function QuoteForm({data:d,requestId}:{data:WorkspaceData;requestId?:string}) {
 const open=d.requests.filter(r=>["OPEN","QUOTING"].includes(r.status));
 const [selected,setSelected]=useState(requestId??open[0]?.id??"");
 const req=d.requests.find(r=>r.id===selected);
 if(!req)return <p>Gere uma lista de compras antes de registrar a cotação.</p>;
 return <Panel title="Registrar cotação" description="Informe preços, disponibilidade e condições de cada fornecedor."><label className="field">Lista de compras<select value={selected} onChange={e=>setSelected(e.target.value)}>{open.map(r=><option key={r.id} value={r.id}>Lista #{r.id.slice(-6)} · {r.items.length} ingredientes</option>)}</select></label><CommandForm key={req.id} command="createQuote" fields={[{name:"supplierId",label:"Fornecedor",options:d.suppliers.filter(s=>s.active).map(s=>({value:s.id,label:s.name}))},{name:"freight",label:"Frete (R$)",type:"number",step:"0.01",min:"0",value:"0"},{name:"leadTimeDays",label:"Prazo de entrega (dias)",type:"number",step:"1",min:"0",value:"0"},{name:"validUntil",label:"Validade",type:"date",required:false},{name:"paymentTerms",label:"Forma e prazo de pagamento",required:false},{name:"qualityNotes",label:"Qualidade / condições adicionais",required:false}]} hidden={{purchaseRequestId:req.id}} transform={v=>({...v,validUntil:v.validUntil||undefined,items:req.items.map(i=>({productId:i.productId,quantity:v[`qty_${i.productId}`],unitPrice:v[`price_${i.productId}`],available:v[`available_${i.productId}`]==="on"}))})} submit="Salvar cotação"><div className="wide-field table-scroll"><table><thead><tr><th>Ingrediente</th><th>Quantidade</th><th>Preço unitário (R$)</th><th>Disponível</th></tr></thead><tbody>{req.items.map(i=><tr key={i.id}><td>{i.product.name}<small>Solicitado: {quantity(i.requestedQuantity)} {label(i.product.unit)}</small></td><td><input aria-label={`Quantidade ${i.product.name}`} name={`qty_${i.productId}`} type="number" min="0.0001" step="0.0001" defaultValue={i.requestedQuantity} required/></td><td><input aria-label={`Preço ${i.product.name}`} name={`price_${i.productId}`} type="number" min="0" step="0.0001" required/></td><td><input aria-label={`Disponível ${i.product.name}`} type="checkbox" name={`available_${i.productId}`} defaultChecked/></td></tr>)}</tbody></table></div></CommandForm></Panel>;
}
