import { test,expect } from "@playwright/test";
test("clientes: cadastro, duplicidade, perfil e pedido com cadastro rápido",async({page},testInfo)=>{
 const suffix=Date.now()+"-"+testInfo.project.name,errors:string[]=[];
 page.on("pageerror",e=>errors.push(e.message));
 await page.goto("/cadastro");
 await page.getByLabel("Nome do restaurante").fill("Clientes UI "+suffix);
 await page.getByLabel("Seu nome").fill("Responsável UI");
 await page.getByLabel("E-mail",{exact:true}).fill("customers-"+suffix+"@example.test");
 await page.getByLabel("Senha",{exact:true}).fill("TesteUI@123456");
 await page.getByRole("button",{name:"Criar restaurante",exact:true}).click();
 await expect(page).toHaveURL(/dashboard/);
 await page.goto("/clientes/novo");
 await page.getByLabel("Nome do cliente",{exact:true}).fill("Cliente UI");
 await page.getByLabel("Telefone",{exact:true}).fill("(11) 99999-1234");
 await page.getByLabel("E-mail",{exact:true}).fill("cliente@example.test");
 await page.getByLabel("Cliente autorizou receber comunicações de marketing").check();
 await page.getByRole("button",{name:"Cadastrar cliente",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Cliente UI",exact:true})).toBeVisible();
 await expect(page.getByRole("link",{name:"Abrir WhatsApp"})).toHaveAttribute("href","https://wa.me/5511999991234");
 await expect(page.getByText("Marketing: Autorizado em",{exact:false})).toBeVisible();
 await page.getByLabel("Nome do cliente",{exact:true}).fill("Cliente UI editado");
 await page.getByRole("button",{name:"Salvar alterações"}).click();
 await expect(page.getByRole("heading",{name:"Cliente UI editado",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Inativar cliente",exact:true}).click();
 await expect(page.getByText("Cliente inativo",{exact:true})).toBeVisible();
 // Editing an inactive client must not accidentally reactivate it.
 await page.getByLabel("Observações",{exact:true}).fill("Contato de demonstração");
 await page.getByRole("button",{name:"Salvar alterações"}).click();
 await expect(page.getByText("Cliente inativo",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Ativar cliente",exact:true}).click();
 await expect(page.getByText("Cliente ativo",{exact:true})).toBeVisible();
 await page.goto("/clientes");
 await page.getByLabel("Buscar cliente",{exact:true}).fill("cliente@example.test");
 await page.getByRole("button",{name:"Buscar",exact:true}).click();
 await expect(page.getByRole("row").filter({hasText:"Cliente UI editado"})).toBeVisible();
 await page.goto("/pedidos");
 await page.getByRole("button",{name:"Cardápio",exact:true}).click();
 await page.getByLabel("Nome do item").first().fill("Quibe cliente UI");
 await page.getByLabel("Preço de venda (R$)").first().fill("20.00");
 await page.getByRole("button",{name:"Adicionar ao cardápio"}).click();
 await expect(page.getByRole("status")).toContainText("Salvo com sucesso");
 await page.getByRole("button",{name:"Novo pedido",exact:true}).click();
 await page.getByRole("combobox",{name:"Tipo",exact:true}).selectOption("TAKEAWAY");
 await page.getByRole("button",{name:"Cadastrar cliente neste pedido"}).click();
 await page.getByLabel("Nome do cliente",{exact:true}).fill("Familiar UI");
 await page.getByLabel("Telefone",{exact:true}).fill("+55 11 99999-1234");
 await expect(page.getByRole("status").filter({hasText:"Possível duplicidade"})).toBeVisible();
 const item=await page.getByRole("combobox",{name:"Item 1",exact:true}).locator("option").filter({hasText:"Quibe cliente UI"}).getAttribute("value");
 await page.getByRole("combobox",{name:"Item 1",exact:true}).selectOption(item!);
 await page.getByRole("button",{name:"Criar pedido",exact:true}).last().click();
 await expect(page.locator(".order-card").filter({hasText:"Familiar UI"})).toBeVisible();
 await page.getByRole("button",{name:"Enviar para cozinha"}).click();
 await page.goto("/cozinha");
 await page.getByRole("button",{name:"Iniciar preparo"}).click();
 await page.getByRole("button",{name:"Marcar como pronto"}).click();
 await page.getByRole("button",{name:"Entregue / finalizar"}).click();
 await expect(page.locator(".kitchen-ticket")).toHaveCount(0);
 await page.goto("/clientes");
 await page.getByRole("row").filter({hasText:"Familiar UI"}).getByRole("link",{name:"Ver perfil"}).click();
 await expect(page.locator(".metrics")).toContainText("20,00");
 await expect(page.getByRole("row").filter({hasText:"Quibe cliente UI"})).toContainText("Finalizado");
 await expect(page.getByText("Marketing: Não autorizado",{exact:true})).toBeVisible();
 await page.screenshot({path:"test-results/clientes-perfil-"+testInfo.project.name+".png",fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto("/pedidos");
 await page.getByRole("button",{name:"Novo pedido",exact:true}).click();
 await page.getByRole("combobox",{name:"Tipo",exact:true}).selectOption("TAKEAWAY");
 await page.getByLabel("Buscar cliente cadastrado",{exact:true}).fill("cliente@example.test");
 await expect(page.getByLabel("Cliente cadastrado (opcional)").locator("option").filter({hasText:"Cliente UI editado"})).toHaveCount(1);
 const selected=await page.getByLabel("Cliente cadastrado (opcional)").locator("option").filter({hasText:"Cliente UI editado"}).getAttribute("value");
 await page.getByLabel("Cliente cadastrado (opcional)").selectOption(selected!);
 await page.getByRole("combobox",{name:"Item 1",exact:true}).selectOption(item!);
 await page.getByRole("button",{name:"Criar pedido",exact:true}).last().click();
 await expect(page.locator(".order-card").filter({hasText:"Cliente UI editado"})).toBeVisible();
 expect(errors).toEqual([]);
});
