import { test,expect } from "@playwright/test";
import QRCode from "qrcode";
import { accessKey,invoiceXml } from "../fixtures/fiscal";
test("pedidos, cozinha, XML e QR funcionam na interface",async({page},testInfo)=>{
 const suffix=Date.now().toString(),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.addInitScript(()=>{Object.defineProperty(window,"BarcodeDetector",{value:undefined,configurable:true});});
 await page.goto("/cadastro");await page.getByLabel("Nome do restaurante").fill("Casa Anatolia UI novos "+suffix);await page.getByLabel("Seu nome").fill("Responsável UI");await page.getByLabel("E-mail",{exact:true}).fill("new-"+suffix+"@example.test");await page.getByLabel("Senha",{exact:true}).fill("TesteUI@123456");await page.getByRole("button",{name:"Criar restaurante",exact:true}).click();await expect(page).toHaveURL(/dashboard/);
 await page.goto("/estoque/produtos/novo");await page.getByLabel("Nome do ingrediente").fill("Carne fiscal UI");await page.getByRole("combobox",{name:"Unidade",exact:true}).selectOption("KG");await page.getByLabel("Estoque mínimo").fill("1");await page.getByLabel("Estoque ideal").fill("20");await page.getByRole("button",{name:"Cadastrar ingrediente",exact:true}).click();await expect(page.getByRole("status")).toHaveText("Salvo com sucesso.");
 await page.goto("/pedidos");await page.getByRole("button",{name:"Cardápio",exact:true}).click();await page.getByLabel("Nome do item").first().fill("Quibe UI");await page.getByLabel("Preço de venda (R$)").first().fill("15.90");await page.getByRole("button",{name:"Adicionar ao cardápio"}).click();await expect(page.getByRole("status")).toHaveText("Salvo com sucesso.");
 await page.getByRole("button",{name:"Novo pedido",exact:true}).click();await page.getByLabel("Mesa",{exact:true}).fill("12");const menuValue=await page.getByRole("combobox",{name:"Item 1",exact:true}).locator("option").filter({hasText:"Quibe UI"}).getAttribute("value");await page.getByRole("combobox",{name:"Item 1",exact:true}).selectOption(menuValue!);await page.getByLabel("Quantidade",{exact:true}).fill("2");await page.getByLabel("Observação do item").fill("Sem cebola");await page.getByLabel("Observação geral").fill("Cliente aguardando");await page.getByRole("button",{name:"Criar pedido",exact:true}).last().click();await expect(page.getByRole("status")).toContainText("Pedido criado");
 await expect(page.locator(".order-card")).toContainText("31,80");await page.getByRole("button",{name:"Enviar para cozinha"}).click();await expect(page.getByText("Enviado à cozinha",{exact:true})).toBeVisible();
 await page.goto("/cozinha");await expect(page.getByText("Sem cebola",{exact:true})).toBeVisible();await page.screenshot({path:"test-results/cozinha-"+testInfo.project.name+".png",fullPage:true});await page.getByRole("button",{name:"Iniciar preparo"}).click();await expect(page.getByRole("region",{name:"Em preparo"}).getByText("Quibe UI",{exact:false})).toBeVisible();await page.getByRole("button",{name:"Marcar como pronto"}).click();await expect(page.getByRole("button",{name:"Entregue / finalizar"})).toBeVisible();
 const original=page.viewportSize()!;await page.setViewportSize({width:1024,height:768});await page.screenshot({path:"test-results/cozinha-tablet-"+testInfo.project.name+".png",fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.setViewportSize(original);
 await page.getByRole("button",{name:"Entregue / finalizar"}).click();await expect(page.locator(".kitchen-ticket")).toHaveCount(0);
 await page.goto("/compras/importar-nota");await page.getByRole("button",{name:"QR Code",exact:true}).click();await expect(page.getByRole("region",{name:"Leitor de QR Code"})).toBeVisible();await page.getByRole("button",{name:"Upload de XML",exact:true}).click();await page.getByLabel("Arquivo XML").setInputFiles({name:"nota-ficticia.xml",mimeType:"application/xml",buffer:Buffer.from(invoiceXml())});await expect(page.getByRole("heading",{name:"Conferência da importação"})).toBeVisible();const product=await page.getByLabel("Produto Casa Anatolia 1").locator("option").filter({hasText:"Carne fiscal UI"}).getAttribute("value");await page.getByLabel("Produto Casa Anatolia 1").selectOption(product!);await page.getByLabel("Lembrar associação").check();await page.screenshot({path:"test-results/importacao-"+testInfo.project.name+".png",fullPage:true});await page.getByRole("button",{name:"Confirmar importação",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Confirmar",exact:true}).click();await expect(page.getByRole("heading",{name:"Importação concluída"})).toBeVisible();
 await page.goto("/estoque/produtos");await expect(page.getByRole("row").filter({hasText:"Carne fiscal UI"})).toContainText("10 kg");
 await page.goto("/financeiro/contas-pagar");await expect(page.getByRole("cell",{name:/Compra - Distribuidora Fiscal/})).toBeVisible();
 await page.goto("/compras/importar-nota");await page.getByRole("button",{name:"QR Code",exact:true}).click();await expect(page.getByRole("region",{name:"Leitor de QR Code"})).toBeVisible();await page.getByRole("button",{name:"Upload de XML",exact:true}).click();await page.getByLabel("Arquivo XML").setInputFiles({name:"duplicada.xml",mimeType:"application/xml",buffer:Buffer.from(invoiceXml())});await expect(page.locator("main").getByRole("alert")).toContainText("já foi importada");
 await page.getByRole("button",{name:"QR Code",exact:true}).click();const qr=await QRCode.toBuffer("https://www.nfce.fazenda.sp.gov.br/qrcode?p="+accessKey(2)+"|2|1|HASH",{type:"png",width:700,margin:4});await page.getByLabel("Imagem do QR Code").setInputFiles({name:"qr.png",mimeType:"image/png",buffer:qr});await expect(page.getByLabel("Chave fiscal (opcional na entrada manual)")).toHaveValue(accessKey(2));
 await page.goto("/dashboard");await page.getByLabel("Busca global").fill("Carne fiscal");await expect(page.getByRole("link",{name:/IngredienteCarne fiscal UI|Ingrediente Carne fiscal UI/})).toBeVisible();await page.getByLabel("Busca global").fill("");
 if(testInfo.project.name==="celular"){await page.getByRole("button",{name:"Abrir menu"}).click();await expect(page.getByRole("dialog",{name:"Menu principal"})).toBeVisible();await page.getByRole("button",{name:"Fechar menu"}).click();await page.getByRole("button",{name:"Filtros",exact:true}).click();await expect(page.getByRole("dialog",{name:"Filtros do período"})).toBeVisible();await page.getByRole("button",{name:"Fechar filtros"}).click();}
 await page.screenshot({path:"test-results/redesign-dashboard-"+testInfo.project.name+".png",fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.goto("/configuracoes");await page.getByLabel("Nome").first().fill("Cozinha UI");await page.getByLabel("E-mail").fill("k-"+suffix+"@example.test");await page.getByLabel("Senha inicial").fill("TesteUI@123456");await page.getByLabel("Perfil").selectOption("KITCHEN");await page.getByRole("button",{name:"Cadastrar usuário",exact:true}).click();await expect(page.getByRole("status")).toHaveText("Salvo com sucesso.");
 if(testInfo.project.name==="celular")await page.getByRole("button",{name:"Abrir menu"}).click();await page.getByRole("button",{name:"Sair",exact:true}).click();await expect(page).toHaveURL(/login/);await page.getByLabel("E-mail",{exact:true}).fill("k-"+suffix+"@example.test");await page.getByLabel("Senha",{exact:true}).fill("TesteUI@123456");await page.getByRole("button",{name:"Entrar",exact:true}).click();await expect(page).toHaveURL(/cozinha/);
 const permissions=await page.evaluate(async()=>({search:(await fetch("/api/search?q=carne")).status,reports:(await fetch("/api/reports")).status,kitchen:await (await fetch("/api/cozinha")).json()}));expect(permissions.search).toBe(403);expect(permissions.reports).toBe(403);expect(JSON.stringify(permissions.kitchen)).not.toContain("total");await page.goto("/financeiro");await expect(page).toHaveURL(/cozinha/);
 expect(errors).toEqual([]);
});
