import { test, expect } from "@playwright/test";
test("família completa o fluxo pela interface",async({page},testInfo)=>{
 const suffix=Date.now().toString();
 await page.goto("/cadastro");
 await page.getByLabel("Nome do restaurante").fill(`Restaurante teste UI ${suffix}`);
 await page.getByLabel("Seu nome").fill("Responsável Teste");
 await page.getByLabel("E-mail",{exact:true}).fill(`ui-${suffix}@example.test`);
 await page.getByLabel("Senha",{exact:true}).fill("TesteUI@123456");
 await page.getByRole("button",{name:"Criar restaurante",exact:true}).click();
 await expect(page).toHaveURL(/dashboard/);
 await page.goto("/estoque/produtos/novo");
 await page.getByLabel("Nome do ingrediente").fill("Grão para teste UI");
 await page.getByRole("combobox",{name:"Unidade",exact:true}).selectOption("KG");
 await page.getByLabel("Estoque mínimo").fill("4");
 await page.getByLabel("Estoque ideal").fill("15");
 await page.getByRole("button",{name:"Cadastrar ingrediente",exact:true}).click();
 await expect(page.getByRole("status")).toHaveText("Salvo com sucesso.");
 await page.goto("/estoque/inventarios");
 await page.getByRole("button",{name:"Iniciar inventário"}).click();
 await page.getByRole("link",{name:"Continuar contagem"}).click();
 await page.getByLabel("Contagem de Grão para teste UI").fill("10");
 await page.getByRole("button",{name:"Finalizar inventário e ajustar estoque"}).click();
 await expect(page.getByText("Finalizado",{exact:true})).toBeVisible();
 await page.goto("/estoque/movimentacoes");
 await page.getByRole("combobox",{name:"Ingrediente",exact:true}).selectOption({label:"Grão para teste UI (kg)"});
 await page.getByRole("combobox",{name:"Tipo",exact:true}).selectOption("CONSUMPTION");
 await page.getByLabel("Quantidade na unidade cadastrada").fill("7");
 await page.getByLabel("Motivo / observações").fill("Produção do restaurante");
 await page.getByRole("button",{name:"Registrar movimentação",exact:true}).click();
 await expect(page.getByRole("status")).toHaveText("Salvo com sucesso.");
 await page.goto("/compras/necessidades");
 await expect(page.getByRole("cell",{name:"12 kg",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Gerar lista do estoque mínimo"}).click();
 await page.goto("/fornecedores/novo");
 await page.getByLabel("Nome do fornecedor").fill("Fornecedor da família");
 await page.getByRole("button",{name:"Cadastrar fornecedor",exact:true}).click();
 await expect(page.getByRole("status")).toHaveText("Salvo com sucesso.");
 await page.goto("/compras/cotacoes");
 await page.getByRole("combobox",{name:"Fornecedor",exact:true}).selectOption({label:"Fornecedor da família"});
 await page.getByLabel("Preço Grão para teste UI").fill("20");
 await page.getByRole("button",{name:"Salvar cotação"}).click();
 await page.getByRole("link",{name:"Avaliar e escolher"}).click();
 await page.getByLabel("Motivo da escolha").fill("Entrega rápida e qualidade aprovada pela família");
 await page.getByRole("button",{name:"Selecionar fornecedor e criar pedido"}).click();
 await page.getByRole("link",{name:"Abrir pedido desta cotação"}).click();
 for(const name of ["Solicitar aprovação","Aprovar compra","Confirmar pedido ao fornecedor"]){await page.getByRole("button",{name,exact:true}).click();}
 const receiptResponse=page.waitForResponse(r=>r.url().endsWith("/api/commands")&&r.request().postDataJSON()?.command==="receivePurchaseOrder");
 await page.getByRole("button",{name:"Confirmar recebimento",exact:true}).click();
 expect((await receiptResponse).ok()).toBeTruthy();
 await expect(page.locator(".order-overview").getByText("Recebido",{exact:true})).toBeVisible();
 await page.goto("/financeiro/contas-pagar");
 await expect(page.getByRole("cell",{name:/Compra - Fornecedor da família/})).toBeVisible();
 const paymentResponse=page.waitForResponse(r=>r.url().endsWith("/api/commands")&&r.request().postDataJSON()?.command==="payFinancialEntry");
 await page.getByRole("button",{name:"Marcar como pago"}).click();
 expect((await paymentResponse).ok()).toBeTruthy();
 await expect(page.getByRole("button",{name:"Marcar como pago"})).toHaveCount(0);
 await page.goto("/dashboard");
 await expect(page.getByRole("cell",{name:"Grão para teste UI",exact:true}).first()).toBeVisible();
 await page.screenshot({path:`test-results/dashboard-${testInfo.project.name}.png`,fullPage:true,scale:"css"});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
