"use client";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { LayoutDashboard,Package,ShoppingCart,Truck,Wallet,ChartNoAxesCombined,Settings,UtensilsCrossed,LogOut,Menu,X,ChefHat,ClipboardList,Users } from "lucide-react";
import { useEffect,useRef,useState,type ReactNode } from "react";
import { Button } from "./ui/button";
import { label } from "./display";
import { SearchInput } from "./global-search";
const navigation=[{href:"/dashboard",name:"Dashboard",icon:LayoutDashboard},{href:"/pedidos",name:"Pedidos",icon:ClipboardList},{href:"/clientes",name:"Clientes",icon:Users},{href:"/cozinha",name:"Cozinha",icon:ChefHat},{href:"/estoque",name:"Estoque",icon:Package},{href:"/compras",name:"Compras",icon:ShoppingCart},{href:"/fornecedores",name:"Fornecedores",icon:Truck},{href:"/financeiro",name:"Financeiro",icon:Wallet},{href:"/relatorios",name:"Relatórios",icon:ChartNoAxesCombined},{href:"/configuracoes",name:"Configurações",icon:Settings}];
const submenus:Record<string,{href:string;name:string}[]>={"/estoque":[{href:"/estoque/produtos",name:"Ingredientes"},{href:"/estoque/movimentacoes",name:"Movimentações"},{href:"/estoque/inventarios",name:"Inventários"}],"/compras":[{href:"/compras/necessidades",name:"Necessidades"},{href:"/compras/listas",name:"Listas"},{href:"/compras/cotacoes",name:"Cotações"},{href:"/compras/pedidos",name:"Pedidos de compra"},{href:"/compras/importar-nota",name:"Importar nota"}],"/financeiro":[{href:"/financeiro/lancamentos",name:"Lançamentos"},{href:"/financeiro/contas-pagar",name:"Contas a pagar"},{href:"/financeiro/categorias",name:"Categorias"}]};
export function AppShell({children,organization,user,role}:{children:ReactNode;organization:string;user:string;role:string}) {
 const path=usePathname(),router=useRouter(),[open,setOpen]=useState(false),drawer=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const admin=["OWNER","ADMIN"].includes(role),finance=["OWNER","ADMIN","VIEWER"].includes(role),orders=["OWNER","ADMIN","OPERATOR"].includes(role),kitchen=orders||role==="KITCHEN";
 const links=navigation.filter(n=>role==="KITCHEN"?n.href==="/cozinha":(n.href!=="/financeiro"||finance)&&(n.href!=="/configuracoes"||admin)&&(n.href!=="/pedidos"||orders)&&(n.href!=="/clientes"||orders)&&(n.href!=="/cozinha"||kitchen));
 useEffect(()=>{if(open){drawer.current?.showModal();document.body.style.overflow="hidden";}else{drawer.current?.close();document.body.style.overflow="";}return()=>{document.body.style.overflow="";};},[open]);
 const close=()=>{setOpen(false);trigger.current?.focus();};
 const contents=<><Link href={role==="KITCHEN"?"/cozinha":"/dashboard"} onClick={close} className="brand"><span className="brand-icon"><UtensilsCrossed size={24}/></span><span>Casa Anatolia<span className="brand-sub">Restaurante turco</span></span></Link><div className="organization-name">{organization}</div><nav aria-label="Navegação principal">{links.map(({href,name,icon:Icon})=><div key={href}><Link href={href} onClick={close} className={path.startsWith(href)?"nav-link active":"nav-link"} aria-current={path.startsWith(href)?"page":undefined}><Icon size={20}/>{name}</Link>{path.startsWith(href)&&submenus[href]&&<div className="nav-submenu">{submenus[href].filter(s=>!s.href.endsWith("importar-nota")||orders).map(s=><Link key={s.href} href={s.href} onClick={close} aria-current={path===s.href?"page":undefined}>{s.name}</Link>)}</div>}</div>)}</nav><div className="sidebar-foot"><span className="avatar">{user.slice(0,1)}</span><div><strong>{user}</strong><small>{label(role)}</small></div><Button variant="ghost" size="icon" aria-label="Sair" onClick={async()=>{const r=await fetch("/api/auth/logout",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(r.ok){router.push("/login");router.refresh();}}}><LogOut size={19}/></Button></div></>;
 return <div className="app-shell"><aside className="sidebar desktop-sidebar">{contents}</aside><dialog ref={drawer} className="mobile-navigation" aria-label="Menu principal" onCancel={close}><Button className="drawer-close" variant="ghost" size="icon" aria-label="Fechar menu" onClick={close}><X/></Button>{contents}</dialog><div className="app-content"><header className="topbar"><Button ref={trigger} className="mobile-menu-button" variant="ghost" size="icon" aria-label="Abrir menu" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></Button><Link href={role==="KITCHEN"?"/cozinha":"/dashboard"} className="mobile-wordmark">Casa Anatolia</Link>{role!=="KITCHEN"&&<SearchInput/>}<div className="header-user"><span className="avatar">{user.slice(0,1)}</span><span>{user}<small>{label(role)}</small></span></div></header><main id="main-content">{children}</main><footer className="app-footer">Casa Anatolia · Restaurante turco</footer></div></div>;
}
