"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { UtensilsCrossed } from "lucide-react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
export function AuthForm({register=false}:{register?:boolean}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState("");const router=useRouter();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);try{const r=await fetch(`/api/auth/${register?"register":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const d=await r.json();if(!r.ok)throw new Error(d.error);router.push("/dashboard");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Não foi possível entrar. Tente novamente.");}finally{setBusy(false);}}
 return <main className="auth-page" id="main-content"><div className="auth-intro"><div className="auth-wordmark"><UtensilsCrossed size={28}/> Casa Anatolia</div><div className="auth-brand-sub">Restaurante turco</div><h1>Gestão simples<br/>para seu restaurante.</h1><p>Estoque, compras, pedidos e finanças organizados em um só lugar.</p><div className="auth-intro-foot">Feito para a rotina de quem cuida do restaurante.</div></div><div className="auth-form-wrap"><div className="auth-form"><h2>{register?"Organize seu restaurante":"Bem-vindo à Casa Anatolia"}</h2><p>{register?"Crie a organização e sua conta de proprietário.":"Entre para acompanhar o dia a dia."}</p><form onSubmit={submit}>{register&&<><label className="field">Nome do restaurante<Input name="organizationName" required autoComplete="organization" minLength={2}/></label><label className="field">Seu nome<Input name="name" required autoComplete="name" minLength={2}/></label></>}<label className="field">E-mail<Input name="email" type="email" required autoComplete="username"/></label><div className="field"><label htmlFor="auth-password">Senha</label><Input id="auth-password" name="password" type="password" required minLength={register?10:1} autoComplete={register?"new-password":"current-password"} aria-describedby={register?"password-hint":undefined}/>{register&&<small id="password-hint">Ao menos 10 caracteres, com letras e números.</small>}</div>{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?"Aguarde…":register?"Criar restaurante":"Entrar"}</Button></form><p className="auth-link">{register?"Já tem uma conta?":"Primeira vez por aqui?"} <Link href={register?"/login":"/cadastro"}>{register?"Entrar":"Criar restaurante"}</Link></p><p className="privacy-note">Cada restaurante tem seus próprios dados e permissões.</p></div></div></main>;
}
