"use client";
import Link from "next/link";
import { useState } from "react";
import type { WorkspaceData } from "@/modules/dashboard";
import { Button } from "@/shared/components/ui/button";
import { CommandForm, type Field } from "@/shared/components/command-form";
import { Panel, Table, Empty, currency, date, label, quantity } from "@/shared/components/display";
export function SuppliersView({data:d,parts}:{data:WorkspaceData;parts:string[]}) {
 const [search,setSearch]=useState("");const id=parts[1],s=d.suppliers.find(s=>s.id===id),buyer=["OWNER","ADMIN","BUYER"].includes(d.user.role);
 const fields:Field[]=[{name:"name",label:"Nome do fornecedor",value:s?.name},{name:"companyName",label:"Razão social",required:false,value:s?.companyName??undefined},{name:"document",label:"CPF / CNPJ",required:false,value:s?.document??undefined},{name:"phone",label:"Telefone",type:"tel",required:false,value:s?.phone??undefined},{name:"whatsapp",label:"WhatsApp (contato)",type:"tel",required:false,value:s?.whatsapp??undefined},{name:"email",label:"E-mail",type:"email",required:false,value:s?.email??undefined},{name:"address",label:"Endereço",required:false,value:s?.address??undefined},{name:"notes",label:"Observações",required:false,value:s?.notes??undefined}];
 return <><div className="page-heading"><div><h1>Fornecedores</h1><p>Organize seus contatos e compare condições de compra.</p></div>{buyer&&<Button asChild><Link href="/fornecedores/novo">Novo fornecedor</Link></Button>}</div>{id&&(id==="novo"||s)?<>{buyer&&<Panel title={s?"Dados do fornecedor":"Cadastrar fornecedor"}><CommandForm command={s?"updateSupplier":"createSupplier"} fields={fields} hidden={s?{id:s.id,active:s.active}:{}} submit={s?"Salvar fornecedor":"Cadastrar fornecedor"}/></Panel>}{s&&<>{buyer&&<Panel title="Registrar preço" description="Cada atualização preserva o preço anterior no histórico."><CommandForm command="setSupplierPrice" hidden={{supplierId:s.id}} fields={[{name:"productId",label:"Ingrediente",options:d.products.filter(p=>p.active).map(p=>({value:p.id,label:`${p.name} (${label(p.unit)})`}))},{name:"price",label:"Preço unitário (R$)",type:"number",step:"0.0001",min:"0"},{name:"minimumOrderQuantity",label:"Quantidade mínima de compra",type:"number",step:"0.0001",min:"0",value:"0"},{name:"leadTimeDays",label:"Prazo (dias)",type:"number",step:"1",min:"0",value:"0"},{name:"paymentTerms",label:"Condições de pagamento",required:false},{name:"notes",label:"Observações / qualidade",required:false}]} submit="Registrar preço e condições"/></Panel>}<Panel title={`Preços · ${s.name}`} description="Preço por unidade cadastrada; condições não substituem negociação com o fornecedor.">{s.products.length===0?<Empty>Nenhum preço registrado.</Empty>:<Table headers={["Ingrediente","Último preço","Mínimo","Prazo","Pagamento","Histórico"]}>{s.products.map(sp=><tr key={sp.id}><td>{sp.product.name}</td><td>{currency(sp.lastPrice)} / {label(sp.product.unit)}</td><td>{quantity(sp.minimumOrderQuantity)} {label(sp.product.unit)}</td><td>{sp.leadTimeDays} dias</td><td>{sp.paymentTerms??"—"}</td><td><details><summary>Ver preços anteriores</summary>{sp.priceHistory.map(h=><small key={h.id}>{date(h.date)} · {currency(h.price)} · {h.source==="PURCHASE"?"Compra":h.source==="QUOTE"?"Cotação":"Pesquisa"}</small>)}</details></td></tr>)}</Table>}</Panel></>}</>:<Panel title="Seus fornecedores" action={<input className="search-input" aria-label="Buscar fornecedor" placeholder="Buscar fornecedor…" value={search} onChange={e=>setSearch(e.target.value)}/>}>{d.suppliers.length===0?<Empty>Cadastre fornecedores para começar a pesquisar preços.</Empty>:<Table headers={["Fornecedor","Contato","Ingredientes","Situação","Ação"]}>{d.suppliers.filter(s=>s.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.companyName}</small></td><td>{s.phone??s.whatsapp??"—"}<small>{s.email}</small></td><td>{s.products.length}</td><td>{s.active?"Ativo":"Inativo"}</td><td><Link className="text-link" href={`/fornecedores/${s.id}`}>Contato e preços</Link></td></tr>)}</Table>}</Panel>}</>;
}
