"use client";
import { useEffect,useState } from "react";
import { ChefHat,Clock,CheckCheck } from "lucide-react";
import { executeCommand } from "@/shared/components/command-form";
import { PageHeader } from "@/shared/components/design-system";
import { Empty,label } from "@/shared/components/display";
import { Button } from "@/shared/components/ui/button";
export type KitchenOrder={id:string;number:number;type:string;tableName:string|null;customerName:string|null;notes:string|null;status:string;sentToKitchenAt:string;items:{id:string;name:string;quantity:number;notes:string|null}[]};
const lanes=[{status:"SENT_TO_KITCHEN",name:"Novos",action:"Iniciar preparo",next:"PREPARING",icon:Clock},{status:"PREPARING",name:"Em preparo",action:"Marcar como pronto",next:"READY",icon:ChefHat},{status:"READY",name:"Prontos",action:"Entregue / finalizar",next:"COMPLETED",icon:CheckCheck}];
export function KitchenView({initial}:{initial:KitchenOrder[]}){
 const [orders,setOrders]=useState(initial),[now,setNow]=useState(()=>Date.now()),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[updated,setUpdated]=useState(false);
 useEffect(()=>{let active=true;const c=new AbortController();let polling=false;async function poll(){if(polling||document.hidden)return;polling=true;try{const r=await fetch("/api/cozinha",{signal:c.signal,cache:"no-store"});if(!r.ok)throw Error("Não foi possível atualizar os pedidos.");const data=await r.json();if(active){setOrders(previous=>JSON.stringify(previous)===JSON.stringify(data.orders)?previous:data.orders);setNow(Date.now());setUpdated(true);setError("");}}catch(e){if(active&&!c.signal.aborted)setError(e instanceof Error?e.message:"Falha na atualização.");}finally{polling=false;}}const timer=setInterval(poll,4000);void poll();return()=>{active=false;c.abort();clearInterval(timer);};},[]);
 return <><PageHeader title="Cozinha" description="Prepare, confira e entregue. Atualização automática a cada 4 segundos." actions={<span className="badge badge-ok">{updated?"Atualização ativa":"Conectando…"}</span>}/>{error&&<p role="alert" className="form-error">{error} A lista anterior foi preservada.</p>}<div className="kitchen-board">{lanes.map(l=><section className="kitchen-lane" key={l.status} aria-label={l.name}><header><h2><l.icon size={22}/>{l.name}</h2><span className="badge">{orders.filter(o=>o.status===l.status).length}</span></header>{orders.filter(o=>o.status===l.status).map(o=><article className="kitchen-ticket" key={o.id}><div className="ticket-heading"><h3>#{o.number}</h3><span><Clock size={16}/>{Math.max(0,Math.floor((now-new Date(o.sentToKitchenAt).getTime())/60000))} min</span></div><p>{o.type==="TABLE"?"Mesa "+o.tableName:label(o.type)}{o.customerName?" · "+o.customerName:""}</p><ul>{o.items.map(i=><li key={i.id}><strong><span>{i.quantity}×</span> {i.name}</strong>{i.notes&&<p className="ticket-note">{i.notes}</p>}</li>)}</ul>{o.notes&&<p className="ticket-note">Pedido: {o.notes}</p>}<Button disabled={busy===o.id} onClick={async()=>{setBusy(o.id);try{await executeCommand("transitionOrder",{id:o.id,status:l.next});const r=await fetch("/api/cozinha",{cache:"no-store"});if(!r.ok)throw Error("Pedido atualizado. Aguardando sincronização.");setOrders((await r.json()).orders);setError("");}catch(e){setError(e instanceof Error?e.message:"Não foi possível atualizar.");}finally{setBusy(null);}}}>{busy===o.id?"Atualizando…":l.action}</Button></article>)}{!orders.some(o=>o.status===l.status)&&<Empty>Nenhum pedido {l.status==="READY"?"pronto":l.status==="PREPARING"?"em preparo":"novo"}.</Empty>}</section>)}</div></>;
}
