import Link from "next/link";
import { ArrowRight, TriangleAlert, PackageCheck, ShoppingBasket, Wallet } from "lucide-react";
import type { WorkspaceData } from "../index";
import { Badge, currency, date, Empty, label, Panel, quantity, Table } from "@/shared/components/display";
import { Button } from "@/shared/components/ui/button";
import { PeriodFilter } from "@/shared/components/period-filter";
export function DashboardView({data:d}:{data:WorkspaceData}) {
 const pending=d.orders.filter(o=>!["RECEIVED","CANCELED"].includes(o.status));
 return <><div className="page-heading"><div><h1>Visão geral</h1><p>Acompanhe o restaurante e organize os próximos passos.</p></div><Button asChild><Link href="/estoque/movimentacoes">Registrar movimentação</Link></Button></div><PeriodFilter {...d.period}/>{d.user.email.endsWith("@exemplo.com")&&<div className="demo-note">Ambiente de demonstração · Todos os dados são fictícios.</div>}{d.products.length===0&&<Panel title="Vamos organizar a casa?" description="Comece pelos ingredientes e faça uma contagem física do estoque."><div className="onboarding-steps"><Link href="/estoque/produtos/novo">1. Cadastrar ingredientes <ArrowRight size={16}/></Link><Link href="/estoque/inventarios/novo">2. Fazer inventário inicial <ArrowRight size={16}/></Link><Link href="/fornecedores/novo">3. Cadastrar fornecedores <ArrowRight size={16}/></Link><Link href="/financeiro/lancamentos">4. Registrar receitas e despesas <ArrowRight size={16}/></Link></div></Panel>}
 {d.financeVisible&&<div className="metrics"><article className="metric metric-feature"><span>Saldo de caixa</span><strong>{currency(d.summary.balance)}</strong><small>Receitas e despesas já pagas, desde o início</small></article><article className="metric"><span>Entradas no período</span><strong className="positive">{currency(d.summary.income)}</strong><small>Dinheiro recebido</small></article><article className="metric"><span>Saídas no período</span><strong>{currency(d.summary.expenses)}</strong><small>Despesas pagas</small></article><article className="metric"><span>Resultado do período</span><strong className={Number(d.summary.result)<0?"negative":"positive"}>{currency(d.summary.result)}</strong><small>Entradas menos saídas</small></article></div>}
 <div className="dashboard-columns"><Panel title="Precisam da sua atenção" description="Ingredientes que chegaram ao estoque mínimo." action={<Link className="text-link" href="/compras/necessidades">Ver lista <ArrowRight size={15}/></Link>}>{d.alerts.length===0?<Empty><PackageCheck size={24}/>O estoque está em dia.</Empty>:<div className="alert-list">{d.alerts.slice(0,5).map(p=><div className="stock-alert" key={p.id}><TriangleAlert size={18}/><div><strong>{p.name}</strong><small>{quantity(p.currentStock)} {label(p.unit)} em estoque · mínimo {quantity(p.minimumStock)} {label(p.unit)}</small></div><span>Comprar <strong>{quantity(p.suggestedQuantity)} {label(p.unit)}</strong></span></div>)}</div>}<div className="panel-bottom"><span>{d.alerts.length} ingrediente{d.alerts.length!==1?"s":""} na lista de compras</span><Button asChild variant="outline" size="sm"><Link href="/compras/necessidades">Organizar compras</Link></Button></div></Panel><Panel title="Próximos passos"><div className="task-list"><Link href="/compras/pedidos"><ShoppingBasket size={20}/><span>Compras em andamento<small>Acompanhe aprovações e entregas</small></span><strong>{pending.length}</strong></Link><Link href="/estoque/inventarios"><PackageCheck size={20}/><span>Inventários abertos<small>Conclua as contagens físicas</small></span><strong>{d.counts.filter(c=>c.status==="OPEN").length}</strong></Link>{d.financeVisible&&<Link href="/financeiro/contas-pagar"><Wallet size={20}/><span>Contas a pagar<small>{currency(d.summary.payable)} em compromissos</small></span><strong>{d.summary.payableCount}</strong></Link>}</div>{d.financeVisible&&<div className="purchase-total"><span>Compras recebidas no período</span><strong>{currency(d.summary.purchases)}</strong><small>Inclui compras com pagamento pendente</small></div>}</Panel></div>
 <div className="dashboard-columns"><Panel title="Últimas movimentações" description="As mais recentes dentro do período selecionado.">{d.movements.length===0?<Empty>Nenhuma movimentação no período.</Empty>:<Table headers={["Ingrediente","Movimentação","Quantidade","Data"]}>{d.movements.slice(0,6).map(m=><tr key={m.id}><td><strong>{m.product.name}</strong><small>{m.creator.name}</small></td><td><Badge value={m.type}/></td><td className={m.direction==="OUT"?"negative":"positive"}>{m.direction==="OUT"?"−":"+"}{quantity(m.quantity)} {label(m.product.unit)}</td><td>{date(m.createdAt)}</td></tr>)}</Table>}</Panel><Panel title="Consumo do período" description="Ordenado pelo custo dos ingredientes consumidos.">{d.consumption.length===0?<Empty>Registre o consumo para acompanhar os ingredientes.</Empty>:<Table headers={["Ingrediente","Consumo","Custo"]}>{d.consumption.slice(0,6).map(c=><tr key={c.product.id}><td>{c.product.name}</td><td>{quantity(c.quantity)} {label(c.product.unit)}</td><td>{currency(c.cost)}</td></tr>)}</Table>}</Panel></div>
 <Panel title="Últimas compras" action={<Link className="text-link" href="/compras/pedidos">Todos os pedidos <ArrowRight size={15}/></Link>}>{d.orders.length===0?<Empty>Nenhum pedido cadastrado.</Empty>:<Table headers={["Pedido","Fornecedor","Status","Valor","Detalhes"]}>{d.orders.slice(0,5).map(o=><tr key={o.id}><td>#{o.id.slice(-6).toUpperCase()}</td><td>{o.supplier.name}</td><td><Badge value={o.status}/></td><td>{currency(o.total)}</td><td><Link className="text-link" href={`/compras/pedidos/${o.id}`}>Abrir <ArrowRight size={14}/></Link></td></tr>)}</Table>}</Panel>
 </>;
}
