import Link from "next/link";
import { ArrowRight,PackageCheck,ShoppingBasket,Wallet,ArrowDownLeft,ArrowUpRight,ShoppingCart,ChartNoAxesCombined } from "lucide-react";
import type { WorkspaceData } from "../index";
import { Badge,currency,date,Empty,label,Panel,quantity,Table } from "@/shared/components/display";
import { Button } from "@/shared/components/ui/button";
import { PeriodFilter } from "@/shared/components/period-filter";
import { PageHeader,StatCard } from "@/shared/components/design-system";
import { FinancialChart } from "@/shared/components/financial-chart";
export function DashboardView({data:d}:{data:WorkspaceData}) {
 const expired=d.quotes.filter(q=>q.status==="RECEIVED"&&q.validUntil&&new Date(q.validUntil)<new Date()).length;
 function comparison(type:string,current:string){const prior=Number(d.previousTotals.find(r=>r.type===type)?._sum.amount??0);if(prior===0)return "Sem base no período anterior";const change=(Number(current)-prior)/prior*100;return (change>=0?"+":"")+change.toLocaleString("pt-BR",{maximumFractionDigits:1})+"% em relação ao período anterior";}
 return <><PageHeader title="Dashboard" description="Visão geral da operação e dos próximos passos." actions={<Button asChild><Link href="/estoque/movimentacoes">Registrar movimentação</Link></Button>}/><PeriodFilter {...d.period}/>{d.user.email.endsWith("@exemplo.com")&&<div className="demo-note">Ambiente de demonstração · Todos os dados são fictícios.</div>}{d.products.length===0&&<Panel title="Vamos organizar a casa?" description="Comece pelos ingredientes e faça uma contagem física do estoque."><div className="onboarding-steps"><Link href="/estoque/produtos/novo">1. Cadastrar ingredientes <ArrowRight size={16}/></Link><Link href="/estoque/inventarios/novo">2. Fazer inventário inicial <ArrowRight size={16}/></Link><Link href="/fornecedores/novo">3. Cadastrar fornecedores <ArrowRight size={16}/></Link><Link href="/financeiro/lancamentos">4. Registrar receitas e despesas <ArrowRight size={16}/></Link></div></Panel>}
 {d.financeVisible&&<div className="metrics"><StatCard label="Receitas" value={currency(d.summary.income)} icon={ArrowDownLeft} tone="positive" hint={comparison("INCOME",d.summary.income)}/><StatCard label="Despesas" value={currency(d.summary.expenses)} icon={ArrowUpRight} hint={comparison("EXPENSE",d.summary.expenses)}/><StatCard label="Compras" value={currency(d.summary.purchases)} icon={ShoppingCart} hint="Recebidas no período, incluindo contas pendentes"/><StatCard label="Resultado" value={currency(d.summary.result)} icon={ChartNoAxesCombined} tone={Number(d.summary.result)<0?"negative":"positive"} hint="Receitas recebidas menos despesas pagas"/></div>}
 <div className="dashboard-columns">{d.financeVisible&&<Panel title="Movimentação financeira" description="Receitas recebidas e despesas pagas no período."><FinancialChart rows={d.financialSeries}/><div className="panel-bottom"><span>Saldo de caixa desde o início</span><strong>{currency(d.summary.balance)}</strong></div></Panel>}<Panel title="Estoque em atenção" description={d.alerts.length+" ingredientes precisam de reposição"} action={<Link className="text-link" href="/compras/necessidades">Ver todos <ArrowRight size={15}/></Link>}>{d.alerts.length===0?<Empty><PackageCheck size={24}/>O estoque está em dia.</Empty>:<Table headers={["Ingrediente","Estoque","Status"]}>{d.alerts.slice(0,5).map(p=><tr key={p.id}><td><Link href="/compras/necessidades"><strong>{p.name}</strong><small>Mínimo {quantity(p.minimumStock)} {label(p.unit)}</small></Link></td><td>{quantity(p.currentStock)} {label(p.unit)}</td><td><span className={"badge "+(Number(p.currentStock)===0?"badge-danger":"badge-warn")}>{Number(p.currentStock)===0?"Em falta":"Estoque baixo"}</span></td></tr>)}</Table>}<div className="panel-bottom"><span>{d.alerts.length} itens em atenção</span><Button asChild variant="outline" size="sm"><Link href="/compras/necessidades">Organizar compras</Link></Button></div></Panel></div>
 <div className="dashboard-columns"><Panel title="Últimas movimentações" description="As mais recentes dentro do período selecionado.">{d.movements.length===0?<Empty>Nenhuma movimentação no período.</Empty>:<Table headers={["Ingrediente","Movimentação","Quantidade","Data"]}>{d.movements.slice(0,6).map(m=><tr key={m.id}><td><strong>{m.product.name}</strong><small>{m.creator.name}</small></td><td><Badge value={m.type}/></td><td>{m.direction==="OUT"?"−":"+"}{quantity(m.quantity)} {label(m.product.unit)}</td><td>{date(m.createdAt)}</td></tr>)}</Table>}</Panel><Panel title="Próximos passos"><div className="task-list"><Link href="/compras/pedidos"><ShoppingBasket size={20}/><span>Compras em andamento<small>Acompanhe aprovações e entregas</small></span><strong>{d.summary.pendingOrders}</strong></Link><Link href="/estoque/inventarios"><PackageCheck size={20}/><span>Inventários abertos<small>Conclua as contagens físicas</small></span><strong>{d.counts.filter(c=>c.status==="OPEN").length}</strong></Link>{expired>0&&<Link href="/compras/cotacoes"><ShoppingCart size={20}/><span>Cotações vencidas<small>Confira a validade antes de comprar</small></span><strong>{expired}</strong></Link>}{d.financeVisible&&<Link href="/financeiro/contas-pagar"><Wallet size={20}/><span>Contas a pagar<small>{currency(d.summary.payable)} em compromissos · {d.overdueCount} vencidos</small></span><strong>{d.summary.payableCount}</strong></Link>}</div></Panel></div>
 <div className="dashboard-columns"><Panel title="Últimas compras" action={<Link className="text-link" href="/compras/pedidos">Todos os pedidos <ArrowRight size={15}/></Link>}>{d.orders.length===0?<Empty>Nenhum pedido de compra. Organize uma lista e compare cotações.</Empty>:<Table headers={["Pedido","Fornecedor","Status","Valor","Detalhes"]}>{d.orders.slice(0,5).map(o=><tr key={o.id}><td>#{o.id.slice(-6).toUpperCase()}</td><td>{o.supplier.name}</td><td><Badge value={o.status}/></td><td>{currency(o.total)}</td><td><Link className="text-link" href={"/compras/pedidos/"+o.id}>Abrir <ArrowRight size={14}/></Link></td></tr>)}</Table>}</Panel><Panel title="Consumo do período" description="Ordenado pelo custo dos ingredientes consumidos.">{d.consumption.length===0?<Empty>Registre o consumo para acompanhar os ingredientes.</Empty>:<Table headers={["Ingrediente","Consumo","Custo"]}>{d.consumption.slice(0,6).map(c=><tr key={c.product.id}><td>{c.product.name}</td><td>{quantity(c.quantity)} {label(c.product.unit)}</td><td>{currency(c.cost)}</td></tr>)}</Table>}</Panel></div></>;
}
